import React from "react";
import Head from "next/head";
import Link from "next/link";
import { Heading, Box } from "@chakra-ui/react";

import { Button } from "@/components/elements";

export default function Home() {
  const UserId = "1";
  return (
    <>
      <Head>
        <title>ログインページ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Heading as={"h1"} textAlign={"center"}>
        ログイン画面
      </Heading>
      <Box mt={"16px"} textAlign={"center"}>
        <Link
          href={{
            pathname: `user/${UserId}`,
            query: { userId: UserId },
          }}
          as={`user/${UserId}`}
        >
          <Button colorScheme={"teal"} size={"lg"}>
            ログインする
          </Button>
        </Link>
      </Box>
    </>
  );
}
