import React from "react";
import Head from "next/head";
import { Button } from "@chakra-ui/react";
import { css } from "@emotion/react";

const styles = css`
  color: red;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <p css={styles}>テキスト</p>
      <Button colorScheme="blue">Button</Button>
    </>
  );
}
